#!/bin/python3

def encrypt(text, s):
    result = ""
    # transverse the plain text
    for i in range(len(text)):
        char = text[i]
        # encrypt uppercase characters in plain text
        if char.isupper():
            result += chr((ord(char) + s -65) %26 + 65)
        # encrypt lowercase characters in plain text
        else:
            result += chr((ord(char) + s - 97) % 26 + 97)
    return result

# check the above function
text = input("enter text to encrypt:")
s = 4
print("plain text:", text)
print("shift pattern:", str(s))
print("cipher:", encrypt(text, s))

  
